In [3]:
import torch
from torch import nn
import torch.nn.functional as F

import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
with open('C:\\Works\\Personal\\repo\\PYTORCH_NOTEBOOKS\\Data\\shakespeare.txt','r',encoding='utf8') as f:
    text = f.read()

In [5]:
type(text)

str

In [6]:
print(text[:1000])


                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
  His tender heir might bear his memory:
  But thou contracted to thine own bright eyes,
  Feed'st thy light's flame with self-substantial fuel,
  Making a famine where abundance lies,
  Thy self thy foe, to thy sweet self too cruel:
  Thou that art now the world's fresh ornament,
  And only herald to the gaudy spring,
  Within thine own bud buriest thy content,
  And tender churl mak'st waste in niggarding:
    Pity the world, or else this glutton be,
    To eat the world's due, by the grave and thee.


                     2
  When forty winters shall besiege thy brow,
  And dig deep trenches in thy beauty's field,
  Thy youth's proud livery so gazed on now,
  Will be a tattered weed of small worth held:  
  Then being asked, where all thy beauty lies,
  Where all the treasure of thy lusty days;
  To say within thine own deep su

In [7]:
len(text) #no of characters in the entire text

5445609

In [8]:
all_characters = set(text)

In [9]:
all_characters

{'\n',
 ' ',
 '!',
 '"',
 '&',
 "'",
 '(',
 ')',
 ',',
 '-',
 '.',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 ':',
 ';',
 '<',
 '>',
 '?',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z',
 '[',
 ']',
 '_',
 '`',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z',
 '|',
 '}'}

In [10]:
len(all_characters)

84

In [11]:
for i in enumerate(all_characters):
    print(i)

(0, '|')
(1, '1')
(2, '4')
(3, 'K')
(4, 'n')
(5, 'v')
(6, 'O')
(7, 'P')
(8, 'u')
(9, '\n')
(10, 'l')
(11, '5')
(12, '?')
(13, 'g')
(14, '8')
(15, 's')
(16, 'z')
(17, 'Z')
(18, 'R')
(19, 'J')
(20, 't')
(21, 'y')
(22, '2')
(23, '_')
(24, 'M')
(25, 'o')
(26, 'w')
(27, '`')
(28, ' ')
(29, 'Y')
(30, 'j')
(31, "'")
(32, ',')
(33, 'r')
(34, ')')
(35, ';')
(36, '9')
(37, 'm')
(38, 'a')
(39, 'B')
(40, 'T')
(41, '0')
(42, 'D')
(43, 'W')
(44, 'i')
(45, 'A')
(46, 'f')
(47, '3')
(48, 'x')
(49, 'X')
(50, 'C')
(51, '}')
(52, 'G')
(53, '(')
(54, 'U')
(55, '&')
(56, 'd')
(57, '7')
(58, 'H')
(59, 'p')
(60, '.')
(61, 'N')
(62, '"')
(63, '-')
(64, ']')
(65, '6')
(66, 'E')
(67, 'c')
(68, 'V')
(69, 'e')
(70, '>')
(71, 'b')
(72, 'L')
(73, '!')
(74, '[')
(75, '<')
(76, 'h')
(77, 'I')
(78, 'k')
(79, 'q')
(80, ':')
(81, 'Q')
(82, 'S')
(83, 'F')


In [12]:
decoder = dict(enumerate(all_characters))

In [13]:
decoder

{0: '|',
 1: '1',
 2: '4',
 3: 'K',
 4: 'n',
 5: 'v',
 6: 'O',
 7: 'P',
 8: 'u',
 9: '\n',
 10: 'l',
 11: '5',
 12: '?',
 13: 'g',
 14: '8',
 15: 's',
 16: 'z',
 17: 'Z',
 18: 'R',
 19: 'J',
 20: 't',
 21: 'y',
 22: '2',
 23: '_',
 24: 'M',
 25: 'o',
 26: 'w',
 27: '`',
 28: ' ',
 29: 'Y',
 30: 'j',
 31: "'",
 32: ',',
 33: 'r',
 34: ')',
 35: ';',
 36: '9',
 37: 'm',
 38: 'a',
 39: 'B',
 40: 'T',
 41: '0',
 42: 'D',
 43: 'W',
 44: 'i',
 45: 'A',
 46: 'f',
 47: '3',
 48: 'x',
 49: 'X',
 50: 'C',
 51: '}',
 52: 'G',
 53: '(',
 54: 'U',
 55: '&',
 56: 'd',
 57: '7',
 58: 'H',
 59: 'p',
 60: '.',
 61: 'N',
 62: '"',
 63: '-',
 64: ']',
 65: '6',
 66: 'E',
 67: 'c',
 68: 'V',
 69: 'e',
 70: '>',
 71: 'b',
 72: 'L',
 73: '!',
 74: '[',
 75: '<',
 76: 'h',
 77: 'I',
 78: 'k',
 79: 'q',
 80: ':',
 81: 'Q',
 82: 'S',
 83: 'F'}

In [14]:
decoder.items()

dict_items([(0, '|'), (1, '1'), (2, '4'), (3, 'K'), (4, 'n'), (5, 'v'), (6, 'O'), (7, 'P'), (8, 'u'), (9, '\n'), (10, 'l'), (11, '5'), (12, '?'), (13, 'g'), (14, '8'), (15, 's'), (16, 'z'), (17, 'Z'), (18, 'R'), (19, 'J'), (20, 't'), (21, 'y'), (22, '2'), (23, '_'), (24, 'M'), (25, 'o'), (26, 'w'), (27, '`'), (28, ' '), (29, 'Y'), (30, 'j'), (31, "'"), (32, ','), (33, 'r'), (34, ')'), (35, ';'), (36, '9'), (37, 'm'), (38, 'a'), (39, 'B'), (40, 'T'), (41, '0'), (42, 'D'), (43, 'W'), (44, 'i'), (45, 'A'), (46, 'f'), (47, '3'), (48, 'x'), (49, 'X'), (50, 'C'), (51, '}'), (52, 'G'), (53, '('), (54, 'U'), (55, '&'), (56, 'd'), (57, '7'), (58, 'H'), (59, 'p'), (60, '.'), (61, 'N'), (62, '"'), (63, '-'), (64, ']'), (65, '6'), (66, 'E'), (67, 'c'), (68, 'V'), (69, 'e'), (70, '>'), (71, 'b'), (72, 'L'), (73, '!'), (74, '['), (75, '<'), (76, 'h'), (77, 'I'), (78, 'k'), (79, 'q'), (80, ':'), (81, 'Q'), (82, 'S'), (83, 'F')])

In [15]:
encoder = {char: ind for ind,char in decoder.items()}

In [16]:
encoder

{'|': 0,
 '1': 1,
 '4': 2,
 'K': 3,
 'n': 4,
 'v': 5,
 'O': 6,
 'P': 7,
 'u': 8,
 '\n': 9,
 'l': 10,
 '5': 11,
 '?': 12,
 'g': 13,
 '8': 14,
 's': 15,
 'z': 16,
 'Z': 17,
 'R': 18,
 'J': 19,
 't': 20,
 'y': 21,
 '2': 22,
 '_': 23,
 'M': 24,
 'o': 25,
 'w': 26,
 '`': 27,
 ' ': 28,
 'Y': 29,
 'j': 30,
 "'": 31,
 ',': 32,
 'r': 33,
 ')': 34,
 ';': 35,
 '9': 36,
 'm': 37,
 'a': 38,
 'B': 39,
 'T': 40,
 '0': 41,
 'D': 42,
 'W': 43,
 'i': 44,
 'A': 45,
 'f': 46,
 '3': 47,
 'x': 48,
 'X': 49,
 'C': 50,
 '}': 51,
 'G': 52,
 '(': 53,
 'U': 54,
 '&': 55,
 'd': 56,
 '7': 57,
 'H': 58,
 'p': 59,
 '.': 60,
 'N': 61,
 '"': 62,
 '-': 63,
 ']': 64,
 '6': 65,
 'E': 66,
 'c': 67,
 'V': 68,
 'e': 69,
 '>': 70,
 'b': 71,
 'L': 72,
 '!': 73,
 '[': 74,
 '<': 75,
 'h': 76,
 'I': 77,
 'k': 78,
 'q': 79,
 ':': 80,
 'Q': 81,
 'S': 82,
 'F': 83}

In [17]:
encoded_text = np.array([encoder[char] for char in text])

In [18]:
encoded_text[:500]

array([ 9, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28,
       28, 28, 28, 28, 28,  1,  9, 28, 28, 83, 33, 25, 37, 28, 46, 38, 44,
       33, 69, 15, 20, 28, 67, 33, 69, 38, 20,  8, 33, 69, 15, 28, 26, 69,
       28, 56, 69, 15, 44, 33, 69, 28, 44,  4, 67, 33, 69, 38, 15, 69, 32,
        9, 28, 28, 40, 76, 38, 20, 28, 20, 76, 69, 33, 69, 71, 21, 28, 71,
       69, 38,  8, 20, 21, 31, 15, 28, 33, 25, 15, 69, 28, 37, 44, 13, 76,
       20, 28,  4, 69,  5, 69, 33, 28, 56, 44, 69, 32,  9, 28, 28, 39,  8,
       20, 28, 38, 15, 28, 20, 76, 69, 28, 33, 44, 59, 69, 33, 28, 15, 76,
       25,  8, 10, 56, 28, 71, 21, 28, 20, 44, 37, 69, 28, 56, 69, 67, 69,
       38, 15, 69, 32,  9, 28, 28, 58, 44, 15, 28, 20, 69,  4, 56, 69, 33,
       28, 76, 69, 44, 33, 28, 37, 44, 13, 76, 20, 28, 71, 69, 38, 33, 28,
       76, 44, 15, 28, 37, 69, 37, 25, 33, 21, 80,  9, 28, 28, 39,  8, 20,
       28, 20, 76, 25,  8, 28, 67, 25,  4, 20, 33, 38, 67, 20, 69, 56, 28,
       20, 25, 28, 20, 76

In [19]:
def one_hot_encoder(encoded_text, num_uni_chars):
    '''
    encoded_text : batch of encoded text
    
    num_uni_chars = number of unique characters (len(set(text)))
    '''
    
    # method obtained from:
    # https://stackoverflow.com/questions/29831489/convert-encoded_textay-of-indices-to-1-hot-encoded-numpy-encoded_textay
      
    # creating a placeholder for zeros.
    one_hot = np.zeros((encoded_text.size, num_uni_chars))
    
    # converting data type for later use with pytorch (errors if we dont!)
    one_hot = one_hot.astype(np.float32)

    # using fancy indexing fill in the 1s at the correct index locations
    one_hot[np.arange(one_hot.shape[0]), encoded_text.flatten()] = 1.0
    

    # reshaping it so it matches the batch sahe
    one_hot = one_hot.reshape((*encoded_text.shape, num_uni_chars))
    
    return one_hot

In [20]:
#small example of one hot encoding
arr = np.array([1,2,0])

In [21]:
arr

array([1, 2, 0])

In [22]:
one_hot_encoder(arr, 3)

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

In [23]:
def generate_batches(encoded_text, samp_per_batch=10, seq_len=50):
    
    '''
    Generating (using yield) batches for training.
    
    X: Encoded Text of length seq_len
    Y: Encoded Text shifted by one
    Example:
    X:
    [[1 2 3]]
    
    Y:
    [[ 2 3 4]]
    encoded_text : Completing Encoded Text to make batches from batch_size : Number of samples per batch seq_len : 
    Length of character sequence
       
    '''
    # Total number of characters per batch
    # Example: If samp_per_batch is 2 and seq_len is 50, then 100  characters come out per batch.
    char_per_batch = samp_per_batch * seq_len
    
    
    # Number of batches available to make
    # using int() to roun to nearest integer
    num_batches_avail = int(len(encoded_text)/char_per_batch)
    
    # cutting off end of encoded_text that
    # won't fit evenly into a batch
    encoded_text = encoded_text[:num_batches_avail * char_per_batch]
    
    
    # Reshape text into rows the size of a batch
    encoded_text = encoded_text.reshape((samp_per_batch, -1))
    

    # Go through each row in array.
    for n in range(0, encoded_text.shape[1], seq_len):
        
        # Grab feature characters
        x = encoded_text[:, n:n+seq_len]
        
        # y is the target shifted over by 1
        y = np.zeros_like(x)
       
        #
        try:
            y[:, :-1] = x[:, 1:]
            y[:, -1]  = encoded_text[:, n+seq_len]
            
        # FOR POTENTIAL INDEXING ERROR AT THE END    
        except:
            y[:, :-1] = x[:, 1:]
            y[:, -1] = encoded_text[:, 0]
            
        yield x, y

In [24]:
sample_text = encoded_text[:20]

In [25]:
sample_text

array([ 9, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28,
       28, 28, 28])

In [26]:
batch_generator = generate_batches(sample_text,samp_per_batch=2,seq_len=5) 

In [27]:
x, y  = next(batch_generator)

In [28]:
x

array([[ 9, 28, 28, 28, 28],
       [28, 28, 28, 28, 28]])

In [29]:
y

array([[28, 28, 28, 28, 28],
       [28, 28, 28, 28, 28]])

In [30]:
torch.cuda.is_available()

False