In [0]:
import torch
from torch import nn
import torch.nn.functional as F

import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [0]:
with open('/content/shakespeare.txt','r',encoding='utf8') as f:
    text = f.read()

In [63]:
type(text)

str

In [64]:
print(text[:1000])


                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
  His tender heir might bear his memory:
  But thou contracted to thine own bright eyes,
  Feed'st thy light's flame with self-substantial fuel,
  Making a famine where abundance lies,
  Thy self thy foe, to thy sweet self too cruel:
  Thou that art now the world's fresh ornament,
  And only herald to the gaudy spring,
  Within thine own bud buriest thy content,
  And tender churl mak'st waste in niggarding:
    Pity the world, or else this glutton be,
    To eat the world's due, by the grave and thee.


                     2
  When forty winters shall besiege thy brow,
  And dig deep trenches in thy beauty's field,
  Thy youth's proud livery so gazed on now,
  Will be a tattered weed of small worth held:  
  Then being asked, where all thy beauty lies,
  Where all the treasure of thy lusty days;
  To say within thine own deep su

In [65]:
len(text) #no of characters in the entire text

5445609

In [0]:
all_characters = set(text)

In [67]:
len(all_characters)

84

In [68]:
for i in enumerate(all_characters):
    print(i)

(0, ' ')
(1, '.')
(2, 'T')
(3, 'k')
(4, '1')
(5, 'F')
(6, 'D')
(7, '0')
(8, '7')
(9, 'P')
(10, ';')
(11, 'f')
(12, 'V')
(13, '|')
(14, 'd')
(15, 'M')
(16, 'h')
(17, 'b')
(18, ')')
(19, 's')
(20, '4')
(21, 'K')
(22, 'J')
(23, 'X')
(24, '<')
(25, 'p')
(26, 'L')
(27, '6')
(28, 'R')
(29, '\n')
(30, '"')
(31, '3')
(32, 'Y')
(33, '8')
(34, '}')
(35, '2')
(36, 'u')
(37, '-')
(38, '?')
(39, 'A')
(40, ']')
(41, 'i')
(42, 'a')
(43, 'c')
(44, ':')
(45, 'W')
(46, '5')
(47, '>')
(48, 'r')
(49, '&')
(50, '_')
(51, 'O')
(52, 'U')
(53, 'e')
(54, 'o')
(55, "'")
(56, 'H')
(57, ',')
(58, 'B')
(59, 'z')
(60, 'I')
(61, 'l')
(62, 'q')
(63, '9')
(64, 'w')
(65, 'C')
(66, '(')
(67, 'E')
(68, 'y')
(69, 'Z')
(70, 'x')
(71, 't')
(72, 'j')
(73, '[')
(74, '!')
(75, '`')
(76, 'N')
(77, 'm')
(78, 'g')
(79, 'n')
(80, 'Q')
(81, 'G')
(82, 'S')
(83, 'v')


In [0]:
decoder = dict(enumerate(all_characters))

In [70]:
decoder

{0: ' ',
 1: '.',
 2: 'T',
 3: 'k',
 4: '1',
 5: 'F',
 6: 'D',
 7: '0',
 8: '7',
 9: 'P',
 10: ';',
 11: 'f',
 12: 'V',
 13: '|',
 14: 'd',
 15: 'M',
 16: 'h',
 17: 'b',
 18: ')',
 19: 's',
 20: '4',
 21: 'K',
 22: 'J',
 23: 'X',
 24: '<',
 25: 'p',
 26: 'L',
 27: '6',
 28: 'R',
 29: '\n',
 30: '"',
 31: '3',
 32: 'Y',
 33: '8',
 34: '}',
 35: '2',
 36: 'u',
 37: '-',
 38: '?',
 39: 'A',
 40: ']',
 41: 'i',
 42: 'a',
 43: 'c',
 44: ':',
 45: 'W',
 46: '5',
 47: '>',
 48: 'r',
 49: '&',
 50: '_',
 51: 'O',
 52: 'U',
 53: 'e',
 54: 'o',
 55: "'",
 56: 'H',
 57: ',',
 58: 'B',
 59: 'z',
 60: 'I',
 61: 'l',
 62: 'q',
 63: '9',
 64: 'w',
 65: 'C',
 66: '(',
 67: 'E',
 68: 'y',
 69: 'Z',
 70: 'x',
 71: 't',
 72: 'j',
 73: '[',
 74: '!',
 75: '`',
 76: 'N',
 77: 'm',
 78: 'g',
 79: 'n',
 80: 'Q',
 81: 'G',
 82: 'S',
 83: 'v'}

In [71]:
decoder.items()

dict_items([(0, ' '), (1, '.'), (2, 'T'), (3, 'k'), (4, '1'), (5, 'F'), (6, 'D'), (7, '0'), (8, '7'), (9, 'P'), (10, ';'), (11, 'f'), (12, 'V'), (13, '|'), (14, 'd'), (15, 'M'), (16, 'h'), (17, 'b'), (18, ')'), (19, 's'), (20, '4'), (21, 'K'), (22, 'J'), (23, 'X'), (24, '<'), (25, 'p'), (26, 'L'), (27, '6'), (28, 'R'), (29, '\n'), (30, '"'), (31, '3'), (32, 'Y'), (33, '8'), (34, '}'), (35, '2'), (36, 'u'), (37, '-'), (38, '?'), (39, 'A'), (40, ']'), (41, 'i'), (42, 'a'), (43, 'c'), (44, ':'), (45, 'W'), (46, '5'), (47, '>'), (48, 'r'), (49, '&'), (50, '_'), (51, 'O'), (52, 'U'), (53, 'e'), (54, 'o'), (55, "'"), (56, 'H'), (57, ','), (58, 'B'), (59, 'z'), (60, 'I'), (61, 'l'), (62, 'q'), (63, '9'), (64, 'w'), (65, 'C'), (66, '('), (67, 'E'), (68, 'y'), (69, 'Z'), (70, 'x'), (71, 't'), (72, 'j'), (73, '['), (74, '!'), (75, '`'), (76, 'N'), (77, 'm'), (78, 'g'), (79, 'n'), (80, 'Q'), (81, 'G'), (82, 'S'), (83, 'v')])

In [0]:
encoder = {char: ind for ind,char in decoder.items()}

In [73]:
encoder

{'\n': 29,
 ' ': 0,
 '!': 74,
 '"': 30,
 '&': 49,
 "'": 55,
 '(': 66,
 ')': 18,
 ',': 57,
 '-': 37,
 '.': 1,
 '0': 7,
 '1': 4,
 '2': 35,
 '3': 31,
 '4': 20,
 '5': 46,
 '6': 27,
 '7': 8,
 '8': 33,
 '9': 63,
 ':': 44,
 ';': 10,
 '<': 24,
 '>': 47,
 '?': 38,
 'A': 39,
 'B': 58,
 'C': 65,
 'D': 6,
 'E': 67,
 'F': 5,
 'G': 81,
 'H': 56,
 'I': 60,
 'J': 22,
 'K': 21,
 'L': 26,
 'M': 15,
 'N': 76,
 'O': 51,
 'P': 9,
 'Q': 80,
 'R': 28,
 'S': 82,
 'T': 2,
 'U': 52,
 'V': 12,
 'W': 45,
 'X': 23,
 'Y': 32,
 'Z': 69,
 '[': 73,
 ']': 40,
 '_': 50,
 '`': 75,
 'a': 42,
 'b': 17,
 'c': 43,
 'd': 14,
 'e': 53,
 'f': 11,
 'g': 78,
 'h': 16,
 'i': 41,
 'j': 72,
 'k': 3,
 'l': 61,
 'm': 77,
 'n': 79,
 'o': 54,
 'p': 25,
 'q': 62,
 'r': 48,
 's': 19,
 't': 71,
 'u': 36,
 'v': 83,
 'w': 64,
 'x': 70,
 'y': 68,
 'z': 59,
 '|': 13,
 '}': 34}

In [0]:
encoded_text = np.array([encoder[char] for char in text])

In [75]:
encoded_text[:500]

array([29,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  4, 29,  0,  0,  5, 48, 54, 77,  0, 11, 42, 41,
       48, 53, 19, 71,  0, 43, 48, 53, 42, 71, 36, 48, 53, 19,  0, 64, 53,
        0, 14, 53, 19, 41, 48, 53,  0, 41, 79, 43, 48, 53, 42, 19, 53, 57,
       29,  0,  0,  2, 16, 42, 71,  0, 71, 16, 53, 48, 53, 17, 68,  0, 17,
       53, 42, 36, 71, 68, 55, 19,  0, 48, 54, 19, 53,  0, 77, 41, 78, 16,
       71,  0, 79, 53, 83, 53, 48,  0, 14, 41, 53, 57, 29,  0,  0, 58, 36,
       71,  0, 42, 19,  0, 71, 16, 53,  0, 48, 41, 25, 53, 48,  0, 19, 16,
       54, 36, 61, 14,  0, 17, 68,  0, 71, 41, 77, 53,  0, 14, 53, 43, 53,
       42, 19, 53, 57, 29,  0,  0, 56, 41, 19,  0, 71, 53, 79, 14, 53, 48,
        0, 16, 53, 41, 48,  0, 77, 41, 78, 16, 71,  0, 17, 53, 42, 48,  0,
       16, 41, 19,  0, 77, 53, 77, 54, 48, 68, 44, 29,  0,  0, 58, 36, 71,
        0, 71, 16, 54, 36,  0, 43, 54, 79, 71, 48, 42, 43, 71, 53, 14,  0,
       71, 54,  0, 71, 16

In [0]:
def one_hot_encoder(encoded_text, num_uni_chars):
    '''
    encoded_text : batch of encoded text
    
    num_uni_chars = number of unique characters (len(set(text)))
    '''
    
    # method obtained from:
    # https://stackoverflow.com/questions/29831489/convert-encoded_textay-of-indices-to-1-hot-encoded-numpy-encoded_textay
      
    # creating a placeholder for zeros.
    one_hot = np.zeros((encoded_text.size, num_uni_chars))
    
    # converting data type for later use with pytorch (errors if we dont!)
    one_hot = one_hot.astype(np.float32)

    # using fancy indexing fill in the 1s at the correct index locations
    one_hot[np.arange(one_hot.shape[0]), encoded_text.flatten()] = 1.0
    

    # reshaping it so it matches the batch sahe
    one_hot = one_hot.reshape((*encoded_text.shape, num_uni_chars))
    
    return one_hot

In [0]:
#small example of one hot encoding
arr = np.array([1,2,0])

In [78]:
arr

array([1, 2, 0])

In [79]:
one_hot_encoder(arr, 3)

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

In [0]:
def generate_batches(encoded_text, samp_per_batch=10, seq_len=50):
    
    '''
    Generating (using yield) batches for training.
    
    X: Encoded Text of length seq_len
    Y: Encoded Text shifted by one
    Example:
    X:
    [[1 2 3]]
    
    Y:
    [[ 2 3 4]]
    encoded_text : Completing Encoded Text to make batches from batch_size : Number of samples per batch seq_len : 
    Length of character sequence
       
    '''
    # Total number of characters per batch
    # Example: If samp_per_batch is 2 and seq_len is 50, then 100  characters come out per batch.
    char_per_batch = samp_per_batch * seq_len
    
    
    # Number of batches available to make
    # using int() to roun to nearest integer
    num_batches_avail = int(len(encoded_text)/char_per_batch)
    
    # cutting off end of encoded_text that
    # won't fit evenly into a batch
    encoded_text = encoded_text[:num_batches_avail * char_per_batch]
    
    
    # Reshape text into rows the size of a batch
    encoded_text = encoded_text.reshape((samp_per_batch, -1))
    

    # Go through each row in array.
    for n in range(0, encoded_text.shape[1], seq_len):
        
        # Grab feature characters
        x = encoded_text[:, n:n+seq_len]
        
        # y is the target shifted over by 1
        y = np.zeros_like(x)
       
        #
        try:
            y[:, :-1] = x[:, 1:]
            y[:, -1]  = encoded_text[:, n+seq_len]
            
        # FOR POTENTIAL INDEXING ERROR AT THE END    
        except:
            y[:, :-1] = x[:, 1:]
            y[:, -1] = encoded_text[:, 0]
            
        yield x, y

In [0]:
sample_text = encoded_text[:20]

In [82]:
sample_text

array([29,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0])

In [0]:
batch_generator = generate_batches(sample_text,samp_per_batch=2,seq_len=5) 

In [0]:
x, y  = next(batch_generator)

In [85]:
x

array([[29,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0]])

In [86]:
y

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [87]:
torch.cuda.is_available()

True

In [0]:
use_cuda = True

In [0]:
class CharModel(nn.Module):
    
    def __init__(self, all_chars, num_hidden=256, num_layers=4,drop_prob=0.5,use_gpu=False):
        
        
        # setting up attributes
        super().__init__()
        self.drop_prob = drop_prob
        self.num_layers = num_layers
        self.num_hidden = num_hidden
        self.use_gpu = use_gpu
        
        #CHARACTER SET, ENCODER, and DECODER
        self.all_chars = all_chars
        self.decoder = dict(enumerate(all_chars))
        self.encoder = {char: ind for ind,char in decoder.items()}
        
        
        self.lstm = nn.LSTM(len(self.all_chars), num_hidden, num_layers, dropout=drop_prob, batch_first=True)
        
        self.dropout = nn.Dropout(drop_prob)
        
        self.fc_linear = nn.Linear(num_hidden, len(self.all_chars))
      
    
    def forward(self, x, hidden):
                  
        
        lstm_output, hidden = self.lstm(x, hidden)
        
        
        drop_output = self.dropout(lstm_output)
        
        drop_output = drop_output.contiguous().view(-1, self.num_hidden)
        
        
        final_out = self.fc_linear(drop_output)
        
        
        return final_out, hidden
    
    
    def hidden_state(self, batch_size):
        '''
        Used as separate method to account for both GPU and CPU users.
        '''
        
        if self.use_gpu:
            
            hidden = (torch.zeros(self.num_layers,batch_size,self.num_hidden).cuda(),
                     torch.zeros(self.num_layers,batch_size,self.num_hidden).cuda())
        else:
            hidden = (torch.zeros(self.num_layers,batch_size,self.num_hidden),
                     torch.zeros(self.num_layers,batch_size,self.num_hidden))
        
        return hidden

In [0]:
model = CharModel(
    all_chars=all_characters,
    num_hidden=512,
    num_layers=3,
    drop_prob=0.5,
    use_gpu=True,
)

In [0]:
total_param  = []
for p in model.parameters():
    total_param.append(int(p.numel()))

In [92]:
sum(total_param)

5470292

In [93]:
len(encoded_text)

5445609

In [0]:
optimizer = torch.optim.Adam(model.parameters(),lr=0.001)
criterion = nn.CrossEntropyLoss()

In [0]:
# percentage of data to be used for training
train_percent = 0.1

In [96]:
int(len(encoded_text) * (train_percent))

544560

In [0]:
train_ind = int(len(encoded_text) * (train_percent))

In [0]:
train_data = encoded_text[:train_ind]
val_data = encoded_text[train_ind:]

In [0]:
# Epochs to train for
epochs = 50
# batch size 
batch_size = 128

# Length of sequence
seq_len = 100

# for printing report purposes
# always start at 0
tracker = 0

# number of characters in text
num_char = max(encoded_text)+1

In [100]:
# Set model to train
model.train()


# Check to see if using GPU
if model.use_gpu:
    model.cuda()

for i in range(epochs):
    
    hidden = model.hidden_state(batch_size)
    
    
    for x,y in generate_batches(train_data,batch_size,seq_len):
        
        tracker += 1
        
        # One Hot Encode incoming data
        x = one_hot_encoder(x,num_char)
        
        # Convert Numpy Arrays to Tensor
        
        inputs = torch.from_numpy(x)
        targets = torch.from_numpy(y)
        
        # Adjust for GPU if necessary
        
        if model.use_gpu:
            
            inputs = inputs.cuda()
            targets = targets.cuda()
            
        # Reset Hidden State
        # If we dont' reset we would backpropagate through all training history
        hidden = tuple([state.data for state in hidden])
        
        model.zero_grad()
        
        lstm_output, hidden = model.forward(inputs,hidden)
        loss = criterion(lstm_output,targets.view(batch_size*seq_len).long())
        
        loss.backward()
        
        # POSSIBLE EXPLODING GRADIENT PROBLEM!
        # LET"S CLIP JUST IN CASE
        nn.utils.clip_grad_norm_(model.parameters(),max_norm=5)
        
        optimizer.step()
        
        
        
        ###################################
        ### CHECK ON VALIDATION SET ######
        #################################
        
        if tracker % 25 == 0:
            
            val_hidden = model.hidden_state(batch_size)
            val_losses = []
            model.eval()
            
            for x,y in generate_batches(val_data,batch_size,seq_len):
                
                # One Hot Encode incoming data
                x = one_hot_encoder(x,num_char)
                

                # Convert Numpy Arrays to Tensor

                inputs = torch.from_numpy(x)
                targets = torch.from_numpy(y)

                # Adjust for GPU if necessary

                if model.use_gpu:

                    inputs = inputs.cuda()
                    targets = targets.cuda()
                    
                # Reset Hidden State
                # If we dont' reset we would backpropagate through 
                # all training history
                val_hidden = tuple([state.data for state in val_hidden])
                
                lstm_output, val_hidden = model.forward(inputs,val_hidden)
                val_loss = criterion(lstm_output,targets.view(batch_size*seq_len).long())
        
                val_losses.append(val_loss.item())
            
            # Reset to training model after val for loop
            model.train()
            
            print(f"Epoch: {i} Step: {tracker} Val Loss: {val_loss.item()}")

Epoch: 0 Step: 25 Val Loss: 3.237664222717285
Epoch: 1 Step: 50 Val Loss: 3.2331621646881104
Epoch: 1 Step: 75 Val Loss: 3.2267045974731445
Epoch: 2 Step: 100 Val Loss: 3.089893102645874
Epoch: 2 Step: 125 Val Loss: 2.998598337173462
Epoch: 3 Step: 150 Val Loss: 2.849747896194458
Epoch: 4 Step: 175 Val Loss: 2.766860008239746
Epoch: 4 Step: 200 Val Loss: 2.6719610691070557
Epoch: 5 Step: 225 Val Loss: 2.548754930496216
Epoch: 5 Step: 250 Val Loss: 2.4534506797790527
Epoch: 6 Step: 275 Val Loss: 2.3802664279937744
Epoch: 7 Step: 300 Val Loss: 2.3201465606689453
Epoch: 7 Step: 325 Val Loss: 2.2700226306915283
Epoch: 8 Step: 350 Val Loss: 2.2233948707580566
Epoch: 8 Step: 375 Val Loss: 2.1848795413970947
Epoch: 9 Step: 400 Val Loss: 2.1455702781677246
Epoch: 10 Step: 425 Val Loss: 2.119403600692749
Epoch: 10 Step: 450 Val Loss: 2.089174270629883
Epoch: 11 Step: 475 Val Loss: 2.0637459754943848
Epoch: 11 Step: 500 Val Loss: 2.0452277660369873
Epoch: 12 Step: 525 Val Loss: 2.024680376052856

In [0]:
model_name = 'lstm_on_shakespere.net'

In [0]:
torch.save(model.state_dict(),model_name)

In [0]:
# MUST MATCH THE EXACT SAME SETTINGS AS MODEL USED DURING TRAINING!

model = CharModel(
    all_chars=all_characters,
    num_hidden=512,
    num_layers=3,
    drop_prob=0.5,
    use_gpu=True,
)

In [57]:
model.load_state_dict(torch.load(model_name))
model.eval()

CharModel(
  (lstm): LSTM(83, 512, num_layers=3, batch_first=True, dropout=0.5)
  (dropout): Dropout(p=0.5, inplace=False)
  (fc_linear): Linear(in_features=512, out_features=83, bias=True)
)

In [0]:
def predict_next_char(model, char, hidden=None, k=1):
        
        # Encode raw letters with model
        encoded_text = model.encoder[char]
        
        # set as numpy array for one hot encoding
        # NOTE THE [[ ]] dimensions!!
        encoded_text = np.array([[encoded_text]])
        
        # One hot encoding
        encoded_text = one_hot_encoder(encoded_text, len(model.all_chars))
        
        # Convert to Tensor
        inputs = torch.from_numpy(encoded_text)
        
        # Check for CPU
        if(model.use_gpu):
            inputs = inputs.cuda()
        
        
        # Grab hidden states
        hidden = tuple([state.data for state in hidden])
        
        
        # Run model and get predicted output
        lstm_out, hidden = model(inputs, hidden)

        
        # Convert lstm_out to probabilities
        probs = F.softmax(lstm_out, dim=1).data
        
        
        
        if(model.use_gpu):
            # move back to CPU to use with numpy
            probs = probs.cpu()
        
        
        # k determines how many characters to consider
        # for our probability choice.
        # https://pytorch.org/docs/stable/torch.html#torch.topk
        
        # Return k largest probabilities in tensor
        probs, index_positions = probs.topk(k)
        
        
        index_positions = index_positions.numpy().squeeze()
        
        # Create array of probabilities
        probs = probs.numpy().flatten()
        
        # Convert to probabilities per index
        probs = probs/probs.sum()
        
        # randomly choose a character based on probabilities
        char = np.random.choice(index_positions, p=probs)
       
        # return the encoded value of the predicted char and the hidden state
        return model.decoder[char], hidden

In [0]:
def generate_text(model, size, seed='The', k=1):
        
      
    
    # CHECK FOR GPU
    if(model.use_gpu):
        model.cuda()
    else:
        model.cpu()
    
    # Evaluation mode
    model.eval()
    
    # begin output from initial seed
    output_chars = [c for c in seed]
    
    # intiate hidden state
    hidden = model.hidden_state(1)
    
    # predict the next character for every character in seed
    for char in seed:
        char, hidden = predict_next_char(model, char, hidden, k=k)
    
    # add initial characters to output
    output_chars.append(char)
    
    # Now generate for size requested
    for i in range(size):
        
        # predict based off very last letter in output_chars
        char, hidden = predict_next_char(model, output_chars[-1], hidden, k=k)
        
        # add predicted character
        output_chars.append(char)
    
    # return string of predicted text
    return ''.join(output_chars)

In [60]:
print(generate_text(model, 1000, seed='The ', k=3))

The stand to-this
    And my live of the will to-be their loves,
    That hear the wind the wind of my beauty strangies.
    In him in many, then that heaven of them stand.
    That when the senses and stand, which thoush the strangth
    When he will the strange of the suncine of this count.

                             Enter PAROLLES

  LAFEU. Which the streeks and stard of the sides of thy self.

                            Enter ANTONY

    I would no sold in thy honour to her,  
    Which thou sholld't hate and see a serve to me.


                     111
  That to thy beauten see that sen too lears,
  Which somethow beauty thee which the will,
  We store thee winds to serve the store,
  Which they wishon to thy love to mean,
  And that they seem that they be seen to thee,
  The store one of a maid of this sold,
  And such to me that stood to the treep,
  The both which some thou shall store see they,
  The stores of her shand be so such to store.
  Or to the wander which thou t