In [1]:
import torch

In [2]:
import numpy as np

In [3]:
torch.__version__

'1.1.0'

In [4]:
arr = np.array([1,2,3,4,5])

In [5]:
print(arr)

[1 2 3 4 5]


In [6]:
arr.dtype

dtype('int32')

In [7]:
type(arr)

numpy.ndarray

In [9]:
x = torch.from_numpy(arr)

In [10]:
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [13]:
arr2d = np.arange(0.0,12.0).reshape(4,3)

In [14]:
arr2d

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [17]:
x2 = torch.tensor(arr2d)
#torch.tensor does not get linked with numpy array
#torch.as_tensor gets linked with the actual numpy array's memory in pc

In [18]:
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [21]:
torch.empty(4,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [20]:
torch.zeros(4,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [22]:
torch.ones(4,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [26]:
torch.arange(2,20,2).reshape(3,3)

tensor([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]])

In [37]:
x= torch.zeros(5,2)

In [38]:
x_normal = torch.rand_like(x)

In [39]:
x_normal.shape

torch.Size([5, 2])

In [40]:
x = torch.arange(6).reshape(3,2)

In [41]:
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [42]:
x[:, 1] #grab each row's value from column 1

tensor([1, 3, 5])